services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: open_target_graph_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: open_target_graph
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d open_target_graph" ]
      interval: 5s
      timeout: 5s
      retries: 5

  dagster:
    build:
      context: .
      dockerfile: Dockerfile.dagster
    container_name: open_target_graph_dagster
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      DB_USER: admin
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: open_target_graph
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/dagster/app
    depends_on:
      postgres:
        condition: service_healthy

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: open_target_graph_streamlit
    environment:
      DB_USER: admin
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: open_target_graph
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
